name: matrix deploy

on:
  workflow_dispatch:

jobs:
  be-depoly:
    strategy:
        matrix:
          runner: [prod-a, prod-b]
    runs-on: ${{ matrix.runner }}
      # runs-on: [self-hosted, macOS, X64, prod]
    steps:
      - name: hello
        run: echo "hellow, world!"
      
